### ISSUE TITLE
turn-layout-manager/v1.1 build

### ISSUE THREAD

**Issue by tejada** [cdflynn/turn-layout-manager#3]
Hi Collin, it seems the build for 1.1 has failed in jitpack, do you mind having a look into whenever you can please? Thanks!

Log https://jitpack.io/com/github/cdflynn/turn-layout-manager/v1.1/build.log

**Comment by tejada** [comment]
It seems that it's missing the following imports:

import android.view.ViewGroup;
import android.os.Build;

**Comment by cdflynn** [comment]
Thanks! should be resolved now with v1.2
