### ISSUE TITLE
Problem with snapHelper

### ISSUE THREAD

**Issue by fazel997** [cdflynn/turn-layout-manager#5]
I have a recyclerview with a Custom LayoutManager to make the recyclerview curved.I use TurnLayoutManager libraryto do that.
Also i use snapHelper for my recyclerview to make it easier to select items. Like this:

snapHelper.attachToRecyclerView(myRecyclerview);
But the problem is when I use snapHelper I can't scroll the recyclerview. How can i fix this?

**Comment by cdflynn** [comment]
Snap Helper usage and function is completely unchanged, here's a video of me using it: 
![snap_helper_demo_graphics_interchange_format](https://user-images.githubusercontent.com/3619222/64360936-20633d80-cfd1-11e9-9ba9-d9696770adaf.gif)

And the branch I created for that video:
https://github.com/cdflynn/turn-layout-manager/blob/dcf18f37243fb311f228622b519a1178389c62b3/app/src/main/java/cdflynn/android/sample/turn/MainActivity.java#L71

I'll close this but if you see an issue that I've missed and the causes is rooted in the layout manager, please do post an example branch that re-creates the problem.
