### ISSUE TITLE
scroll item and get index value center 

### ISSUE THREAD

**Issue by naser8646** [cdflynn/turn-layout-manager#6]
Hi
I want after scroll get the index value center of page that means scroll paging not smothing

thanks

**Comment by cdflynn** [comment]
Hi,

As an extension of `LinearLayoutManager`, this is compatible with all existing solutions such as `SnapHelper` (https://developer.android.com/reference/kotlin/androidx/recyclerview/widget/SnapHelper) and `PagerSnapHelper` (https://developer.android.com/reference/androidx/recyclerview/widget/PagerSnapHelper).  It's not up to `TurnLayoutManager` to re-implement those behaviors, you'll have to integrate them the usual way with the tools provided.

I'm going to close this, but if you believe there is a reproducible bug that occurs on `TurnLayoutManager` and _not_ on `LinearLayoutManager`, feel free to re-open with a PR demonstrating the problem and I will check it out.

Thanks!
